import { Transaction, Goal, Insight } from './types';

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: '1',
    title: 'Cửa hàng Uniqlo',
    category: 'Mua sắm',
    amount: 1250000,
    type: 'expense',
    date: '2024-05-24T14:20:00Z',
    method: 'Visa **** 4291',
  },
  {
    id: '2',
    title: 'Lương Techcombank',
    category: 'Thu nhập',
    amount: 35000000,
    type: 'income',
    date: '2024-05-24T09:00:00Z',
    method: 'Chuyển khoản định kỳ',
  },
  {
    id: '3',
    title: 'The Coffee House',
    category: 'Ăn uống',
    amount: 65000,
    type: 'expense',
    date: '2024-05-23T07:30:00Z',
    method: 'Ví MoMo',
  },
  {
    id: '4',
    title: 'Hóa đơn điện',
    category: 'Hóa đơn',
    amount: 2450000,
    type: 'expense',
    date: '2024-05-22T20:00:00Z',
    method: 'Tự động thanh toán',
  },
  {
    id: '5',
    title: 'Dự án tự do',
    category: 'Thu nhập',
    amount: 7500000,
    type: 'income',
    date: '2024-05-21T15:00:00Z',
    method: 'Chuyển khoản ngân hàng',
  },
];

export const MOCK_GOALS: Goal[] = [
  {
    id: '1',
    title: 'Căn hộ Penthouse',
    targetAmount: 2425000000,
    currentAmount: 1575000000,
    deadline: '2026-12-31',
    category: 'Bất động sản',
    priority: 'high',
    status: 'active',
    description: 'Mục tiêu mua nhà tại khu đô thị cao cấp Sala.',
    startDate: '2022-01-12',
    frequency: 'Hàng tháng (ngày 25)',
    interestRate: 6.8,
    sourceAccount: 'Lương (Standard Chartered)',
  },
  {
    id: '2',
    title: 'Du lịch Châu Âu',
    targetAmount: 120000000,
    currentAmount: 50400000,
    deadline: '2024-12-15',
    category: 'Du lịch',
    priority: 'high',
    status: 'active',
  },
  {
    id: '3',
    title: 'Xe hơi Tesla Model 3',
    targetAmount: 1200000000,
    currentAmount: 180000000,
    deadline: '2025-06-01',
    category: 'Tài sản',
    priority: 'medium',
    status: 'active',
  },
  {
    id: '4',
    title: 'Khóa học MBA',
    targetAmount: 450000000,
    currentAmount: 396000000,
    deadline: '2024-09-01',
    category: 'Giáo dục',
    priority: 'medium',
    status: 'active',
  },
  {
    id: '5',
    title: 'Mua laptop mới',
    targetAmount: 35000000,
    currentAmount: 35000000,
    deadline: '2023-12-12',
    category: 'Công nghệ',
    priority: 'medium',
    status: 'completed',
    description: 'Máy trạm sáng tạo cao cấp cho atelier.',
  },
];

export const MOCK_INSIGHTS: Insight[] = [
  {
    id: '1',
    title: 'Tối ưu lãi suất',
    description: 'Bạn có 50 triệu trong tài khoản thanh toán. Chuyển sang tiết kiệm lãi suất cao có thể mang thêm 200.000₫ mỗi tháng.',
    type: 'tip',
  },
  {
    id: '2',
    title: 'Cảnh báo chi tiêu',
    description: 'Chi tiêu ăn uống của bạn cao hơn 15% ngân sách. Hãy thử nấu ăn tại nhà tuần này.',
    type: 'warning',
  },
];
